### PR TITLE
Partner Code Review

### PR DESCRIPTION
**Pull request by NicolasAndrehh**
# Milestone - Project done
This project has been through the following changes since its creation:
1. **List Structure**
    - Add tasks array
    - Add list structure in HTML
    - Add list styling using `Sass` 
    - Add list icons
    - Add `dynamic HTML` to create the task list 

2. **List CRUD**
    - Add `CRUD` methods to the task list
    - Add styles to the task list
    - Add local storage for `checkbox status` and task list array
 
3. **Interactive List**
    - Add module `interactiveFunctions.js`
    - Add a `status update` function
    - Add `clear all completed` function
    - Add functions to `set` and `get` local storage
    - Import all interactive functions to the `TaskList class`
 
*This is a summary of all the previous pull requests of this project, feel free to leave any suggestions about the project down below*

### CODE REVIEW

**Comment by sanieni6** [comment]
# Hi, @NicolasAndrehh  🎉🎉🎉🎉🎉🎉
approve-image
## Congratulations! 🎉 You did a great job on this project.
# Highlights
🚀 No linter errors
🚀 Github flow
🚀 Descriptive pull request
🚀 Good commit messages
🚀 Descriptive readme file
🚀The link in the Readme file works
🚀 Good implementation of Sass
🚀 Good implementation modules on your project

Good job on implementing some of the requirements but I think that you can consider the next suggestions to improve your code:

**Comment by sanieni6** [comment]
Kindly consider using The insertAdjacentHTML() method to create the elements of the list, This could reduce considerately the lines of code:
https://github.com/NicolasAndrehh/To-Do-List/blob/081e410bb967539c882b44b219501deb8b502f72/src/modules/taskListClass.js#L46-L89

**Comment by NicolasAndrehh** [comment]
Hey @sanieni6!
Thank you so much for your feedback, I really appreciate your advice about using the insertAdjacentHTML() method, I'll search about it and implement it 😄👍.

**Review by sanieni6 — APPROVED** [review]
hey @NicolasAndrehh . Good job implementing the changes. Now you are ready to merge with the main branch.
Congratulations 🎊 🎊 🎊 🎊 🎊 🎊

**Pull request merged**
